POST http://localhost:3000/api/projects
Content-Type: application/json

{
    "title": "Offer Language Lessons",
    "introduction": "This website serves as a platform to learn English, German, Spanish, or Czech with Tomas.",
    "source": "private",
    "about": "The webpage was created to attract language learners. It serves as a platform where users can book personalized English, German, Spanish, or Czech lessons with Tomas.",    
    "implementation": "The frontend is built with React and Vite. A Docker image was created from a Dockerfile to run a container instance. The website is deployed online for students to book lessons with Tomas.",
    "tools_frontend": ["React", "Serve", "Material UI"],
    "tools_backend": ["Docker", "Fly.io"],
    "url": "https://www.speakwithtomas.com",
    "likes": 0
}